---
# tasks file for vm-config

- name: update vm
  yum:
    update_only: yes
  become: true

- name: install tools
  yum:
    name: '{{ item }}'
    state: present
  become: true
  with_items:
    - httpd
    - net-tools

- name: start services
  service:
    name: '{{ item }}'
    state: started
  become: true
  with_items:
    - httpd


